### PR TITLE
[V4][Hotfix]Update V2 and V3 bundles

### PR DESCRIPTION
**Pull request by pragnagopa**
Hotfix https://github.com/Azure/azure-functions-docker/releases/tag/4.1.3.1 - update V2 and V3 bundles

### CODE REVIEW

**Review by soninaren — APPROVED** [review]
Looks good to me. The number of files updated looks smaller than before.

**Comment by VpOfEngineering** [comment]
LGTM.

**Comment by pragnagopa** [comment]
> Looks good to me. The number of files updated looks smaller than before. 

This PR is updating V4 files only

**Review by CooperLink — APPROVED** [review]
This LGTM. I will do the work on including non-appservice files in templating soon. So that we can reduce the # of file changes needed in the future even more.

**Review by VpOfEngineering — APPROVED** [review]

**Comment by CooperLink** [comment]
I have reverted this change and force updated the hotfix branch.  I am going to introduce my own PR for these changes and retry to attempt to get past build issues we were seeing

**Pull request merged**
