### PR TITLE
Fix Node.js 16 Core Tools base image

### LINKED ISSUE #558: Node.js 16 core tools container uses Node.js 14
https://github.com/Azure/azure-functions-docker/blob/fb9f07d9b5b9cf497a4b3caacdd92d32c0c76425/host/4/bullseye/amd64/node/node16/node16-core-tools.Dockerfile#L6

/cc @alrod 

#557

### PR DESCRIPTION
**Pull request by anthonychu**
Fixes #558 

@TsuyoshiUshio 

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]

**Comment by TsuyoshiUshio** [comment]
Azure DevOps issue happens on build. we created the same PR as this one, and it works fine we moved to the PR. 
https://github.com/Azure/azure-functions-docker/pull/575

**Pull request closed without merging**
