### PR TITLE
Add bundles 1.5.0 and 2.4.0. Removed 1.4.0 and 2.3.0

### PR DESCRIPTION
**Pull request by yojagad**
Updating bundle versions
Versions added
- 1.5.0
- 2.4.0

Versions removed
- 1.4.0
- 2.3.0

---

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]
To allow auto-upgrade to finish on Linux and Windows before the next No-Fly time line in December, we will not be cutting another host release soon. 
@yojagad  - If this release is  needed in the next 4 weeks, please follow up with @fabiocav and @anirudhgarg  -  to figure out if it is possible to create a linux deployment just for bundles updates.

**Comment by divyagandhii** [comment]
@yojagad - Please revert the change from 2.0-upgrade images.

**Comment by yojagad** [comment]
@divyagandhii Reverted the upgrade images.

**Comment by yojagad** [comment]
pinging for reviews/approvals, please. Is there anything else that needs to be updated ?

**Review by vrdmr — APPROVED** [review]

**Pull request merged**
