### PR TITLE
Update host to 3.0.12915

### PR DESCRIPTION
**Pull request by divyagandhii**

### CODE REVIEW

**Comment by ahmelsayed** [comment]
I can't figure out why the build failed just from the logs. I kicked off another one to check again.

**Comment by divyagandhii** [comment]
> 
> 
> I can't figure out why the build failed just from the logs. I kicked off another one to check again.

Yea I don't know either. Let's retry.

**Comment by divyagandhii** [comment]
> 
> 
> > I can't figure out why the build failed just from the logs. I kicked off another one to check again.
> 
> Yea I don't know either. Let's retry.

I think there's an issue in the java build script. The build failed again with the same error. Adding @amamounelsayed who changed this file recently.

**Comment by amamounelsayed** [comment]
Checking it

**Comment by ahmelsayed** [comment]
https://github.com/Azure/azure-functions-docker/pull/180

**Comment by ahmelsayed** [comment]
@divyagandhii can you rebase on master?

**Pull request merged**
