### PR TITLE
Compress python.Dockerfile (stretch/amd64) to a single layer

### PR DESCRIPTION
**Pull request by lowenna**
Signed-off-by: John Howard <jhoward@microsoft.com>

@ahmelsayed Is there any chance you can try this out and ping me offline with an image I can verify?

### CODE REVIEW

**Comment by jhowardmsft** [comment]
It might need an additional ENV command to add the following which were in your "squished" image I tried:


          "Env": [
                "PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D",
                "PYTHON_VERSION=3.6.8",
                "PYTHON_PIP_VERSION=19.0.3",
                "ACCEPT_EULA=Y",
                "AzureWebJobsScriptRoot=/home/site/wwwroot",
                "HOME=/home",
                "FUNCTIONS_WORKER_RUNTIME=",
                "WORKER_TAG=1.0.0b4",
                "AZURE_FUNCTIONS_PACKAGE_VERSION=1.0.0b3",
                "ASPNETCORE_URLS=http://+:80",
                "DOTNET_RUNNING_IN_CONTAINER=true",
                "ASPNETCORE_VERSION=2.2.3"
            ],

**Comment by ahmelsayed** [comment]
oh wow, that's an interesting way of reducing layers. I'd rather do this to the `mesh` specific image, rather than the `python` image as it does nullify client layer cashing, right? I'll ping you with an image and probably apply the ENV and changes to mesh image in another PR. Thanks for the help John!

**Comment by jhowardmsft** [comment]
> as it does nullify client layer cashing, right?

Correct. That is the one big downside for local testing, but given you're building a production image, I only see benefits :)

**Comment by lowenna** [comment]
Going to close this one. Feel free to carry. I have now retired from Microsoft, so will let someone else take up the baton....

**Pull request closed without merging**
