### PR TITLE
Introduce build pipeline to push KEDA images

### PR DESCRIPTION
**Pull request by JatinSanghvi**
### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by ahmelsayed** [comment]
The change looks good to me. We need to check with MCR team to see if https://github.com/microsoft/mcr/pull/1562 is ok as is, or if we will need to move that part under the `oss` folder/team there.

**Comment by tomkerkhove** [comment]
Just out of curiosity - Why is there a need for this? Can't we just improve the official KEDA images or is it a "whitelisting" thing?

**Comment by ahmelsayed** [comment]
Some internal Azure teams have a requirement to only pull from MCR. MCR SLA is under Azure, which makes any registry outage easier to track for Azure teams compared to external registries. It also simplifies deploying to non-connected/offline Azure environments where only MCR is replicated/available offline. The image is copied as is, so I don't think there is anything to "improve" per se in the official KEDA image. Just the choice of registry it's hosted on.

**Comment by JatinSanghvi** [comment]
@ahmelsayed - Is there a way to make the PR merge build succeed? It is failing since the input variable values are not being passed to the build. Also, if in case we are using a test ACR for PR-validation build, I can remove the hardcoding of ACR location.

**Comment by tomkerkhove** [comment]
> Some internal Azure teams have a requirement to only pull from MCR. MCR SLA is under Azure, which makes any registry outage easier to track for Azure teams compared to external registries. It also simplifies deploying to non-connected/offline Azure environments where only MCR is replicated/available offline. The image is copied as is, so I don't think there is anything to "improve" per se in the official KEDA image. Just the choice of registry it's hosted on.

Thanks for sharing!

**Comment by ahmelsayed** [comment]
@JatinSanghvi not sure how to pass values to the auto PR run. You could set `$VERSION_TAG` default to `main`. I ran it with a value https://azure-functions.visualstudio.com/azure-functions-docker/_build/results?buildId=11662&view=results and it seems fine.

**Review by ahmelsayed — APPROVED** [review]

**Pull request merged**
