### PR TITLE
Add v4 sovereign clouds yaml pipeline

### PR DESCRIPTION
**Pull request by divyagandhisethi**
Releasing new Host versions.
[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)

---

### PR information

- [X] The title of the PR is clear and informative.
- [X] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [X] If applicable, the PR references the bug/issue that it fixes in the description.
- [X] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — CHANGES_REQUESTED** [review]
please update the test as well to include both V3 and V4 sovereign cloud yml files added. This will ensure we do not miss releasing any new images to Soverign clouds

**Review by balag0 — APPROVED** [review]

**Comment by divyagandhisethi** [comment]
> please update the test as well to include both V3 and V4 sovereign cloud yml files added. This will ensure we do not miss releasing any new images to Soverign clouds

@CooperLink will be fixing the tests after this PR is merged.

**Comment by divyagandhisethi** [comment]
> > please update the test as well to include both V3 and V4 sovereign cloud yml files added. This will ensure we do not miss releasing any new images to Soverign clouds
> 
> @CooperLink will be fixing the tests after this PR is merged.

@CooperLink - is this done now? If yes,  @pragnagopa - can you update your review

**Comment by pragnagopa** [comment]
@CooperLink  - Please link the PR where you updated tests

**Comment by CooperLink** [comment]
Here is the update for v3 pipelines. To update the pipelines for v4 just add check_sovereign() to the v4 branches of the script. 
Currently this branch is behind dev and does not have the updates available in dev for https://github.com/Azure/azure-functions-docker/pull/513

Please consider rebasing so that we can include coverage for these pipelines in the same PR

**Comment by CooperLink** [comment]
Rebased off of dev and fixed verification script for sovereign cloud pipelines. 
Tested in all scenarios I can think of for both v3 and v4.

**Review by pragnagopa — APPROVED** [review]

**Pull request merged**
