### PR TITLE
Reduce layers in python.Dockerfile

### PR DESCRIPTION
**Pull request by jhowardmsft**
Signed-off-by: John Howard <jhoward@microsoft.com>

@ahmetsayed Following on from internal email. This will remove 3 layers from the base functions image used to build `mcr.microsoft.com/azure-functions/mesh:2.0.12332`.  Removing 3 layers will remove 3 hot-adds of VHDs to the UtilityVM which should reduce container start time by circa 100ms.

@jterry75 FYI

### CODE REVIEW

**Comment by jterry75** [comment]
LGTM (not a maintainer)

The start ENV block is still 1 full "empty" layer right? But we just don't really have a way to avoid that?

**Comment by jhowardmsft** [comment]
> The start ENV block is still 1 full "empty" layer right? But we just don't really have a way to avoid that?

I'm looking into that, but yes, correct at the moment.

**Comment by jhowardmsft** [comment]
@ahmetsayed Could we get a new release of the whole chain pushed to MCR (if not already - not sure what happens now this is merged) so that the perf team can validate the end-to-end perf gain?

(Would be helpful if you could reply appropriately on the current MSFT internal email thread about this).

Thanks :)

**Comment by jhowardmsft** [comment]
And to clarify - the actual measured increase on my test machine was 533ms for start time, far more than my 100ms estimate.

**Comment by ahmelsayed** [comment]
Thank you @jhowardmsft for your contribution :)

**Pull request merged**
