### PR TITLE
Remove dotnet isolated test from mesh

### PR DESCRIPTION
**Pull request by ankitkumarr**
I had added `dotnet-isolated` test as part of my dotnet 5 PR. However, mesh  images run all tests in  `map`. Mesh doesn't support .NET 5 yet. So for now, I have moved the .NET 5 test out of the map. Once we have added mesh support, I will move it back how I had initially added it.

This will unblock mesh build test failure.

---

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]

**Comment by ankitkumarr** [comment]
Whoops! My branch name had the word `mesh` in it. And our images for PR builds are tagged with branch name. So the test logic was running mesh tests in .NET images as the image name had the word `mesh` (from my branch name) in it :). At least that's what I think happened.

Opened a new PR here with different branch name -- https://github.com/Azure/azure-functions-docker/pull/380

**Pull request closed without merging**
