### PR TITLE
Update python installation script similar to slim buster image and install required libs for python 3.6 Dockerfile.

### PR DESCRIPTION
**Pull request by pdthummar**
Updating python installation script similar to slim buster image and installing required libs for python 3.6 Dockerfile. This is resolution for the following issue: 
Reference:
ICM: 321578474

Ran few http python functions and completed basic testing with updated image. 

Reverting the changes of PR #746 and #752.

Releasing new Host versions.
[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)

---

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — CHANGES_REQUESTED** [review]
Please undo the changes in https://github.com/Azure/azure-functions-docker/pull/752 and  https://github.com/Azure/azure-functions-docker/pull/746

**Comment by pdthummar** [comment]
> Please undo the changes in #752 and #746

Hi @pragnagopa , I didn't do any changes in #752 and #746. I think, Jameson Z created both PRs. Thanks

**Comment by pragnagopa** [comment]
> > Please undo the changes in #752 and #746
> 
> Hi @pragnagopa , I didn't do any changes in #752 and #746. I think, Jameson Z created both PRs. Thanks

Can you please work with @vrdmr to understand the context on the above PRs and undo the changes? Changes in this PR will not solve the problem unless images are produced with the bits in this PR

**Review by gavin-aguiar — APPROVED** [review]

**Comment by gavin-aguiar** [comment]
Tested this image: 
image

**Review by vrdmr — APPROVED** [review]

**Review by pragnagopa — APPROVED** [review]
In future please expand the testing you have done

**Pull request merged**
