### PR TITLE
PowerShell 7.2 tests should only be run on V4 and skip on V3

### LINKED ISSUE #640: PowerShell 7.2 tests should only be run on V4 and skip on V3

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
Resolves https://github.com/Azure/azure-functions-docker/issues/640

Releasing new Host versions.
[V3 Release](PASTE_V3_LINK_HERE)
[V2 Release](PASTE_V2_LINK_HERE)

---

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Review by pragnagopa — APPROVED** [review]
👍

**Comment by CooperLink** [comment]
I tested this in another PR https://github.com/Azure/azure-functions-docker/pull/658

I discussed with Francisco. I think that we should revert this change and close this PR as this change is not necessary.

**Comment by pragnagopa** [comment]
@CooperLink - https://github.com/Azure/azure-functions-docker/issues/640 was specifically opened to reenable the tests - can you explain why this change is not required? is it because `FUNCTIONS_WORKER_RUNTIME_VERSION`  is set to `7.2` in the image itself?

**Comment by CooperLink** [comment]
Yes, I verified using the above test that v3/v4 Powershell tests do not require setting the environment variables via -e due to the variables being set in the images themselves. We do not specify version for any of the other languages.  Powershell 7.2 test do run on v4 powershell 7.2 builds and do not run on v3.  I am planning to meet with Francisco to make sure that I have a full understanding.  But, I am 99.99% sure that this change was never required.

**Comment by CooperLink** [comment]
Reverting this change. Discussed with Francisco and connected with Pragna offline.

**Pull request merged**
