### PR TITLE
Include Software Bill Of Materials in build pipelines

### PR DESCRIPTION
**Pull request by CooperLink**
Due to Software Security Executive Order, our docker files need to produce a SBOM during CI.  This PR adds code to our pipelines to include that sbom. 

Example SBOM generated here :
https://azure-functions.visualstudio.com/azure-functions-docker/_build/results?buildId=13653&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=322bb08c-35d9-5776-a92d-98cacfd99f59
``` 
[INFO] 
[INFO] _______________________________________________________________________________________________________________________________________ 
[INFO] |Component Detector Id         |Detection Time                |# Components Found            |# Explicitly Referenced                 | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |CgManifest                    |0.13 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |CocoaPods                     |0.13 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |CorextCG                      |0.13 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Go                            |0.14 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Gradle                        |0.14 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Ivy (Beta)                    |2.4 seconds                   |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Linux                         |76 seconds                    |384                           |384                                     | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Maven                         |0.13 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |MvnCli                        |2 seconds                     |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Npm                           |0.98 seconds                  |91                            |0                                       | 
[INFO] |NpmWithRoots                  |1.1 seconds                   |86                            |10                                      | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |NuGet                         |0.89 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |NuGetProjectCentric           |0.89 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Pip                           |0.91 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Pnpm                          |0.87 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Ruby                          |0.84 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |RustCrateDetector             |0.84 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |RustCrateV2Detector           |0.84 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |SPDX22SBOM                    |0.12 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Yarn                          |0.84 seconds                  |86                            |10                                      | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Total                         |76 seconds                    |647                           |404                                     | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO]  

```

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [x] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by pragnagopa** [comment]
@Cooperlink  - please rebase . @eliaslopezgt  - please review.

**Comment by pragnagopa** [comment]
cc @nzthiago

**Review by eliaslopezgt — CHANGES_REQUESTED** [review]
@CooperLink I think the only thing missing is to publish an ADO artifact containing the manifest.

**Comment by pragnagopa** [comment]
@Cooperlink - would be great if you can paste sample SBOM output in the PR description

**Comment by CooperLink** [comment]
```
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |SPDX22SBOM                    |0.12 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Yarn                          |0.84 seconds                  |86                            |10                                      | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Total                         |76 seconds                    |647                           |404                                     | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO]  

[INFO] Detection time: 76.0574142 seconds. 
[INFO] Scan Manifest file: /tmp/ScanManifest_20220223165522.json 
##[debug]Wrote 476 package elements in the SBOM.
##[debug]Found value for header Build_DefinitionName in internal metadata.
##[debug]Found value for header Build_BuildId in internal metadata.
##[debug]Relationships array are not supported on this SBOM format.
##[debug]Wrote 477 relationship elements in the SBOM.
##[debug]Building the header object.
##[debug]Found value for header Build_BuildId in internal metadata.
##[debug]Found value for header Build_Repository_Uri in internal metadata.
##[debug]Found value for header Build_SourceBranchName in internal metadata.
##[debug]Found value for header Build_SourceVersion in internal metadata.
##[debug]Building the header object.
##[debug]Found value for header SBOMToolName in internal metadata.
##[debug]Found value for header SBOMToolVersion in internal metadata.
##[debug]Found value for header Build_DefinitionName in internal metadata.
##[debug]Found value for header Build_BuildId in internal metadata.
##[information]Finished execution of the Generate workflow SBOMTelemetry {Result=Success, Errors=ErrorContainer`1 {Count=0, Errors=[]}, Parameters=Configuration {BuildDropPath=ConfigurationSetting`1 {Value="/home/vsts/work/1/s/host", Source=JsonConfig}, BuildComponentPath=ConfigurationSetting`1 {Value="/home/vsts/work/1", Source=JsonConfig}, BuildListFile=null, ManifestPath=null, ManifestDirPath=ConfigurationSetting`1 {Value="/home/vsts/work/1/s/host/_manifest", Source=Default}, OutputPath=null, Parallelism=ConfigurationSetting`1 {Value=8, Source=Default}, Verbosity=ConfigurationSetting`1 {Value=Verbose, Source=CommandLine}, ConfigFilePath=ConfigurationSetting`1 {Value="/home/vsts/work/_temp/SBOM-Config-8f2ce87d-8de9-4c3b-bde1-f0a9dc65b5c9.json", Source=CommandLine}, ManifestInfo=ConfigurationSetting`1 {Value=null, Source=Default}, HashAlgorithm=ConfigurationSetting`1 {Value=SHA256, Source=Default}, RootPathFilter=null, CatalogFilePath=null, ValidateSignature=ConfigurationSetting`1 {Value=False, Source=Default}, IgnoreMissing=ConfigurationSetting`1 {Value=False, Source=Default}, ManifestToolAction=Generate, PackageName=null, PackageVersion=null, FilesList=null, PackagesList=null, TelemetryFilePath=ConfigurationSetting`1 {Value="/home/vsts/work/_temp/Telemetry-b0969e19-31f1-411d-8168-454e52efd3e9.json", Source=JsonConfig}, DockerImagesToScan=ConfigurationSetting`1 {Value="mcr.microsoft.com/dotnet/sdk:5.0,mcr.microsoft.com/dotnet/core/runtime-deps:3.1,azurefunctions.azurecr.io/azure-functions/3.0/dotnet:merge-appservice,azurefunctions.azurecr.io/azure-functions/3.0/dotnet-isolated:merge-dotnet-isolated5.0-appservice", Source=JsonConfig}, ExternalDocumentReferenceListFile=null, AdditionalComponentDetectorArgs=null}, SBOMFormatsUsed=[SBOMFile {SbomFormatName=ManifestInfo {Name="CloudBuildManifest", Version="1.0.0"}, SbomFilePath="/home/vsts/work/1/s/host/_manifest/manifest.json", FileSizeInBytes=61160}, SBOMFile {SbomFormatName=ManifestInfo {Name="SPDX", Version="2.2"}, SbomFilePath="/home/vsts/work/1/s/host/_manifest/spdx_2.2/manifest.spdx.json", FileSizeInBytes=440930}], Timings=[Timing {EventName="Metadata build time for SPDX:2.2 format", TimeSpan="00:00:00.0048293"}, Timing {EventName="Metadata build time for CloudBuildManifest:1.0.0 format", TimeSpan="00:00:00.0063705"}, Timing {EventName="Relationships generation time", TimeSpan="00:00:00.0150402"}, Timing {EventName="Packages generation time", TimeSpan="00:01:19.6377806"}, Timing {EventName="Files generation time", TimeSpan="00:00:00.1714296"}, Timing {EventName="Total generation time", TimeSpan="00:01:19.9055373"}], Switches={}, Exceptions={}}
##[debug]Wrote telemetry object to path /home/vsts/work/_temp/Telemetry-b0969e19-31f1-411d-8168-454e52efd3e9.json

**Comment by CooperLink** [comment]
``` 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |SPDX22SBOM                    |0.12 seconds                  |0                             |0                                       | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Yarn                          |0.84 seconds                  |86                            |10                                      | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO] |Total                         |76 seconds                    |647                           |404                                     | 
[INFO] |______________________________|______________________________|______________________________|________________________________________| 
[INFO]

**Comment by pragnagopa** [comment]
@eliaslopezgt - please review updates. @CooperLink - do rebase the PR

**Comment by CooperLink** [comment]
Rebased branch and updated v4 python

**Comment by pragnagopa** [comment]
@eliaslopezgt / @CooperLink - any remaining work here?

**Review by eliaslopezgt — APPROVED** [review]
looks good to me, thanks and great job. 👍

**Review by balag0 — APPROVED** [review]

**Comment by CooperLink** [comment]
Manifests are published as an artifact for each of the build pipelines at this time.

**Pull request merged**
