### PR TITLE
Updating bundle V1 to 1.8.1 and V2 to 2.6.1

### PR DESCRIPTION
**Pull request by alrod**
### PR information

- [x] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by alrod** [comment]
1. I also found 1.5.0 references:
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/dotnet/dotnet-isolated/dotnet-isolated-appservice.Dockerfile#L16
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/dotnet/dotnet-isolated/dotnet-isolated-slim.Dockerfile#L16
https://github.com/Azure/azure-functions-docker/blob/dev/host/3.0/buster/amd64/dotnet/dotnet-isolated/dotnet-isolated.Dockerfile#L16

Should I change them to 1.8.1?

2."v2 java build" and "v2 powershell build" are failed. I tried to find the pipeline but "View more details on Azure Pipelines" leads to 404. Not sure what's wrong with the builds.

**Comment by TsuyoshiUshio** [comment]
`https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json`
image

```
/usr/share/dotnet/sdk/2.2.207/NuGet.targets(119,5): error : Unable to load the service index for source https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json. [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
/usr/share/dotnet/sdk/2.2.207/NuGet.targets(119,5): error :   The SSL connection could not be established, see inner exception. [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
/usr/share/dotnet/sdk/2.2.207/NuGet.targets(119,5): error :   The remote certificate is invalid according to the validation procedure. [/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj]
```
image
Issued to is different. 

It looks certificate issue. Some blog post says, old NuGet.config issue, however, it looks not the case. Hi @balag0 Have you encountered this case?

Probably, https://www.myget.org/F/aspnetcore-dev/api/v3/index.json is correct.

**Comment by TsuyoshiUshio** [comment]
It looks 
It looks NuGet.config is wrong.  Hi @fabiocav  Do you know the feed AspNetVNext? It looks wrong 
```
root@e73c537a0901:/src/azure-functions-host# cat NuGet.config 
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="azure_app_service" value="https://www.myget.org/F/azure-appservice/api/v2" />
    <add key="azure_app_service_staging" value="https://www.myget.org/F/azure-appservice-staging/api/v2" />
    <add key="buildTools" value="https://www.myget.org/F/30de4ee06dd54956a82013fa17a3accb/" />
    <add key="AspNetVNext" value="https://dotnet.myget.org/F/aspnetcore-dev/api/v3/index.json" />
    <add key="Microsoft.Azure.Functions.PowerShellWorker" value="https://azfunc.pkgs.visualstudio.com/e6a70c92-4128-439f-8012-382fe78d6396/_packaging/Microsoft.Azure.Functions.PowerShellWorker/nuget/v3/index.json" />
  </packageSources>
```

**Comment by TsuyoshiUshio** [comment]
I locally tested, I found this patch will works for the current issue.  Since v2 tag is old so that the feed is up to date anymore,.

_host.2.0/stretch/amd64/java/java8.Dockerfile_  Line 8-10
```
RUN BUILD_NUMBER=$(echo ${HOST_VERSION} | cut -d'.' -f 3) && \
    git clone --branch v${HOST_VERSION} https://github.com/Azure/azure-functions-host /src/azure-functions-host 
RUN cd /src/azure-functions-host && sed -i -e 's/dotnet.myget.org/www.myget.org/' NuGet.config
RUN cd /src/azure-functions-host && \
    HOST_COMMIT=$(git rev-list -1 HEAD) && \
```

However, I found one more issue after that. I'm wondering what is the right solution for it.https://github.com/NuGet/Home/issues/6306

```
/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj : error NU1605: Detected package downgrade: Microsoft.Azure.WebJobs from 3.0.25 to 3.0.23. Reference the package directly from the project to select a different version. 
/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj : error NU1605:  Microsoft.Azure.WebJobs.Script.WebHost -> Microsoft.Azure.WebJobs.Host.Storage 4.0.1 -> Microsoft.Azure.WebJobs (>= 3.0.25) 
/src/azure-functions-host/src/WebJobs.Script.WebHost/WebJobs.Script.WebHost.csproj : error NU1605:  Microsoft.Azure.WebJobs.Script.WebHost -> Microsoft.Azure.WebJobs (>= 3.0.23)
```

**Comment by pragnagopa** [comment]
cc @brettsam

**Comment by pragnagopa** [comment]
@TsuyoshiUshio  - can you help unblock the build for this PR? If move to later version of V2 - then we should

**Comment by TsuyoshiUshio** [comment]
Hi @pragnagopa  
Yes. I talked with Bala, since this is the blocker of the release of extension bundle template for kafka and RabbitMQ update. 
Bala is planning to release v2 new host version. Since the issue is old nuget site and dependency of the old tag of v2. It should be better solution to update v2 with new dependency.  @balag0  Do you know the status? or should I create a PR for the v2?

**Comment by pragnagopa** [comment]
@TsuyoshiUshio /@Brettsam - We do not have to update 2.0 images as we will not be release them any more.  

@brettsam - please update this PR without changes to 2.0 images.

**Comment by TsuyoshiUshio** [comment]
@soninaren We are go without v2 host and try to release v3 then publish the extension bundle to CDN. Sounds good?

**Comment by soninaren** [comment]
> @soninaren We are go without v2 host and try to release v3 then publish the extension bundle to CDN. Sounds good?

That sounds good.

**Comment by pragnagopa** [comment]
@Ankitkumarr - please look at dotnet-isolated images

@TsuyoshiUshio  / @balag0  - fixed the PR - please review

**Comment by pragnagopa** [comment]
Ping for reviews!

**Review by balag0 — APPROVED** [review]

**Pull request merged**
