### PR TITLE
Update PowerShell version

### PR DESCRIPTION
**Pull request by tylerl0706**
To the latest worker build.

cc @pragnagopa @SteveL-MSFT @daxian-dbw @asavaritayal @soninaren @ahmelsayed

### CODE REVIEW

**Comment by ahmelsayed** [comment]
Can you also update https://github.com/Azure/azure-functions-docker/blob/master/host/2.0/stretch/amd64/mesh.Dockerfile#L12

**Comment by tylerl0706** [comment]
@ahmelsayed good catch. Will keep that in mind for next time. All fixed now!

**Comment by tylerl0706** [comment]
@ahmelsayed are there any blockers to merge this in?

**Comment by tylerl0706** [comment]
Thanks @ahmelsayed! What's the release process like for this container to MCR? Just want to check when I can start playing with this :smile:

**Comment by ahmelsayed** [comment]
@tylerl0706  It should be there under `mcr.microsoft.com/azure-functions/powershell:dev` by now (the CI machine builds it on merge), though I'm also building `mcr.microsoft.com/azure-functions/powershell:2.0.12165` and once that's done I'll update the `2.0` tag

**Comment by tylerl0706** [comment]
Awesome. Thanks @ahmelsayed. I'll give it a try tomorrow

**Pull request merged**
