### PR TITLE
Updating bundle version to 2.8.4 and 3.3.0

### PR DESCRIPTION
**Pull request by soninaren**
Releasing new Bundle version: 2.8.4
Releasing new Bundle version: 3.3.0

[Bundle Release](https://azfunc.visualstudio.com/Azure%20Functions/_workitems/edit/1123/)

---

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by CooperLink** [comment]
Please rebase this PR.  v4 Templating has been completed. all -appservice images will be built upon the /base/host.Dockerfile from now on

**Review by pragnagopa — CHANGES_REQUESTED** [review]
Please rebase

**Comment by soninaren** [comment]
Closing this as we have abandoned the bundle releases.

**Comment by miqm** [comment]
> Closing this as we have abandoned the bundle releases.

@soninaren what do you mean by abandoning bundle releases? Does it mean that extension bundles will not be included in images?

**Comment by soninaren** [comment]
> > Closing this as we have abandoned the bundle releases.
> 
> @soninaren what do you mean by abandoning bundle releases? Does it mean that extension bundles will not be included in images?

Apologies for a vague message here. What i meant is that the bundle release for these particular versions have been stopped. We would be sending PR for the next version of bundle likely `2.8.5` and `3.4.0`

**Pull request closed without merging**
