### PR TITLE
Updated Functions host version to 3.0.15417.

### PR DESCRIPTION
**Pull request by kashimiz**
Releasing new Host versions.
[V3 Release](https://github.com/Azure/azure-functions-host/releases/tag/v3.0.15417)

---

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by TsuyoshiUshio** [comment]
I just curious that file change is 44. Last time it was 46. https://github.com/Azure/azure-functions-docker/pull/371/files 
Compared with it, 
This one:  isolated image is newly included
Last one  2.0-upgrade  images are included

isolated image looks good, however, we might need check if `2.0-upgrade` is required. @pragnagopa  Do you know if we need it this time as new release?   For the isolated images, Do we have a pipeline to publish this ? or this time it is not necessary? @kashimiz

**Comment by pragnagopa** [comment]
2.0-upgrade is required. please update host version in files in folder https://github.com/Azure/azure-functions-docker/tree/dev/host/2.0-upgrade with new host version

**Comment by pragnagopa** [comment]
script is missing the step :https://github.com/Azure/azure-functions-docker/issues/384

**Review by TsuyoshiUshio — APPROVED** [review]
LGTM

**Pull request merged**
