### PR TITLE
Add Python 3.11 support

### PR DESCRIPTION
**Pull request by fernandoandreotti**
Releasing new Host versions.
[V4 Release - Python 3.11](PASTE_V3_LINK_HERE)

Attempting to add support to Python 3.11. This is my first PR here, I am unsure how the process should be. Are there any instructions on how to perform local tests? Also how to actually release the image.

---

### PR information

- [x] The title of the PR is clear and informative.
- [x] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [x] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by fernandoandreotti** [comment]
@microsoft-github-policy-service agree

**Comment by fernandoandreotti** [comment]
The current errors are likely to be linked to the current failures on master. I am happy to rebase once that has been resolved. Please let me know otherwise.

**Comment by pdthummar** [comment]
@fernandoandreotti Appreciate your efforts for creating this PR for 3.11. At this time for 3.11, we want to remove the usage of MCR golden images and install python manually which will help for layer resharing and controlling the patch version. I have created [draft PR](https://github.com/Azure/azure-functions-docker/pull/841) as i am waiting on host release to be completed. Closing PR this time. Thanks

**Comment by fernandoandreotti** [comment]
Awesome thanks!

**Pull request closed without merging**
