### PR TITLE
Add Ubuntu 20.04 (focal fossa) images for dotnet

### PR DESCRIPTION
**Pull request by paulgear**
---

This is essentially a clone of the Debian buster amd64 directory, but based on the equivalent Ubuntu base image from mcr.microsoft.com/dotnet/*.  Where an equivalent does not exist, I've left out that build.  This is intended to be a partial solution for the discussion in issue #355.

If there's a better way to do this or I've missed something, please let me know. I'm hoping I'll get a CI build by submitting this - if so, I'll check the results and update if needed.

### PR information

- [ ] The title of the PR is clear and informative.
- [ ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by paulgear** [comment]
It looks like the build logs for this are private.  Please let me know if there's anything further I can do.

**Comment by paulgear** [comment]
I've successfully run the focal build stage in our work AzDO instance, so it would be good to get a peek at your build logs.

**Comment by ahmelsayed** [comment]
/cc @CooperLink 

The change looks ok to me. The CI is failing because it's an external contribution, so it doesn't really run.

**Comment by paulgear** [comment]
Anything further I can do to help improve the chances of this being merged soon?

**Comment by paulgear** [comment]
I'm no longer working with Azure or dotnet, and I assume (hope) this has been handled elsewhere.

**Pull request closed without merging**
