### PR TITLE
Add V4 AppService images , build and release pipelines

### PR DESCRIPTION
**Pull request by balag0**
Testing: Verified all the new docker files build successfully. Functional testing will be done later.

---

### PR information

- [X ] The title of the PR is clear and informative.
- [X ] There are a small number of commits, each of which has an informative message. This means that previously merged commits do not appear in the history of the PR. For information on cleaning up the commits in your pull request, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/development-docs/cleaning-up-commits.md).
- [ ] If applicable, the PR references the bug/issue that it fixes in the description.
- [ ] New Unit tests were added for the changes made and CI is passing.

### CODE REVIEW

**Comment by amamounelsayed** [comment]
@balag0 Question are we planning to upgrade to debian11, I believe it should be release in 2 days? We are currently on debian 10.

**Comment by balag0** [comment]
Yes, v4 images are/will be based on debian11.  If there are specific features that don't work on debian11, individual dockerfiles are free to use debian10 as required temporarily. Identifying such features and updating the dockerfiles is the outside the scope of this PR.

**Comment by balag0** [comment]
> @balag0 Question are we planning to upgrade to debian11, I believe it should be release in 2 days? We are currently on debian 10.

Correct. V4 images will be based on debian11.

**Review by pragnagopa — APPROVED** [review]
LGTM!

**Pull request merged**
